### ISSUE TITLE
MyBatis 설정

### ISSUE THREAD

**Issue by itsjustsora** [f-lab-edu/CO-MEN#10]
## 내용
- MyBatis를 사용하기 위한 기본 설정을 합니다.
- SQL문을 실행할 때 관련 정보를 로깅하기 위해 log4jdbc-log4j2 라이브러리를 사용합니다.
- mapper-location 정보는 추후 디렉토리 생성으로 도메인 별 매퍼 파일을 관리하기 위하여 기존 'mapper/*.xml'에서 'mapper/**/*.xml'로 변경하였습니다.

<br>

## 상세 설정
- log4jdbc-log4j2
```
  level:
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: debug
      connection: off
```
- MyBatis
```
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
```

<br>

## 참고
- [log4jdbc-log4j2](http://log4jdbc.brunorozendo.com/)
- [MyBatis](https://mybatis.org/mybatis-3/ko/configuration.html#properties)

<br>

상세한 내용은 [개인 블로그](https://justsora.tistory.com/140)에서 확인할 수 있습니다.
